[versions]

enonicDefaults = "2.1.5"
xpApp = "4.0.0-A1"
nodeGradle = "7.1.0"

[libraries]

[plugins]
enonic-defaults = { id = "com.enonic.defaults", version.ref = "enonicDefaults" }
enonic-xp-app = { id = "com.enonic.xp.app", version.ref = "xpApp" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
