name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v5

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Set release version from git tag
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          sed -i "s/^version=.*/version=$VERSION/" gradle.properties
          npm version "$VERSION" --no-git-tag-version
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get publishing variables
        id: publish_vars
        uses: enonic/release-tools/publish-vars@master
        env:
          PROPERTIES_PATH: './gradle.properties'
          JAVA_HOME: '' # Unset to avoid interfering with publish-vars action

      - name: Verify release version
        if: steps.publish_vars.outputs.release != 'true'
        run: exit 1

      - name: Set NPM publish tag
        run: |
          if [[ "$RELEASE_VERSION" =~ ^[1-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          else
            echo "NPM_TAG=beta" >> $GITHUB_ENV
          fi

      - name: Build and prepare package with Gradle
        run: ./gradlew preparePackage

      - name: Publish to npm
        working-directory: build/npm-resources
        run: |
          npm install -g npm@latest
          npm publish --tag $NPM_TAG

      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          name: Enonic Page Editor ${{ steps.publish_vars.outputs.version }}
          generate_release_notes: true
          prerelease: ${{ steps.publish_vars.outputs.prerelease == 'true' }}

      - name: Update to next snapshot version
        if: steps.publish_vars.outputs.release == 'true'
        run: |
          NEXT_SNAPSHOT="${{ steps.publish_vars.outputs.nextSnapshot }}"
          sed -i "s/^version=.*/version=$NEXT_SNAPSHOT/" gradle.properties
          npm version "$NEXT_SNAPSHOT" --no-git-tag-version

      - name: Commit and push snapshot version
        if: steps.publish_vars.outputs.release == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: './gradle.properties ./package.json'
          message: 'Updated to next SNAPSHOT version'

